package com.child.programming.base.mapper;

import com.child.programming.base.model.TbCollectCourseDo;
import com.child.programming.base.model.TbCollectCourseDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbCollectCourseDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_course
     *
     * @mbggenerated Sat Apr 13 19:07:58 CST 2019
     */
    int countByExample(TbCollectCourseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_course
     *
     * @mbggenerated Sat Apr 13 19:07:58 CST 2019
     */
    int deleteByExample(TbCollectCourseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_course
     *
     * @mbggenerated Sat Apr 13 19:07:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_course
     *
     * @mbggenerated Sat Apr 13 19:07:58 CST 2019
     */
    int insert(TbCollectCourseDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_course
     *
     * @mbggenerated Sat Apr 13 19:07:58 CST 2019
     */
    int insertSelective(TbCollectCourseDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_course
     *
     * @mbggenerated Sat Apr 13 19:07:58 CST 2019
     */
    List<TbCollectCourseDo> selectByExample(TbCollectCourseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_course
     *
     * @mbggenerated Sat Apr 13 19:07:58 CST 2019
     */
    TbCollectCourseDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_course
     *
     * @mbggenerated Sat Apr 13 19:07:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbCollectCourseDo record, @Param("example") TbCollectCourseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_course
     *
     * @mbggenerated Sat Apr 13 19:07:58 CST 2019
     */
    int updateByExample(@Param("record") TbCollectCourseDo record, @Param("example") TbCollectCourseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_course
     *
     * @mbggenerated Sat Apr 13 19:07:58 CST 2019
     */
    int updateByPrimaryKeySelective(TbCollectCourseDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_course
     *
     * @mbggenerated Sat Apr 13 19:07:58 CST 2019
     */
    int updateByPrimaryKey(TbCollectCourseDo record);
}