package com.child.programming.base.mapper;

import com.child.programming.base.model.TbCollectionWorkDto;
import com.child.programming.base.model.TbCollectionWorkDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbCollectionWorkDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_work
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int countByExample(TbCollectionWorkDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_work
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByExample(TbCollectionWorkDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_work
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_work
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insert(TbCollectionWorkDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_work
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insertSelective(TbCollectionWorkDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_work
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    List<TbCollectionWorkDto> selectByExample(TbCollectionWorkDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_work
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    TbCollectionWorkDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_work
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbCollectionWorkDto record, @Param("example") TbCollectionWorkDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_work
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExample(@Param("record") TbCollectionWorkDto record, @Param("example") TbCollectionWorkDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_work
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKeySelective(TbCollectionWorkDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_work
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKey(TbCollectionWorkDto record);
}