package com.child.programming.base.mapper;

import com.child.programming.base.model.TbExperienceCourseDto;
import com.child.programming.base.model.TbExperienceCourseDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbExperienceCourseDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int countByExample(TbExperienceCourseDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByExample(TbExperienceCourseDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insert(TbExperienceCourseDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insertSelective(TbExperienceCourseDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    List<TbExperienceCourseDto> selectByExample(TbExperienceCourseDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    TbExperienceCourseDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbExperienceCourseDto record, @Param("example") TbExperienceCourseDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExample(@Param("record") TbExperienceCourseDto record, @Param("example") TbExperienceCourseDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKeySelective(TbExperienceCourseDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKey(TbExperienceCourseDto record);
}