package com.child.programming.base.mapper;

import com.child.programming.base.model.TbExperienceCourseDo;
import com.child.programming.base.model.TbExperienceCourseDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbExperienceCourseDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Apr 17 20:47:13 CST 2019
     */
    int countByExample(TbExperienceCourseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Apr 17 20:47:13 CST 2019
     */
    int deleteByExample(TbExperienceCourseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Apr 17 20:47:13 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Apr 17 20:47:13 CST 2019
     */
    int insert(TbExperienceCourseDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Apr 17 20:47:13 CST 2019
     */
    int insertSelective(TbExperienceCourseDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Apr 17 20:47:13 CST 2019
     */
    List<TbExperienceCourseDo> selectByExample(TbExperienceCourseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Apr 17 20:47:13 CST 2019
     */
    TbExperienceCourseDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Apr 17 20:47:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbExperienceCourseDo record, @Param("example") TbExperienceCourseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Apr 17 20:47:13 CST 2019
     */
    int updateByExample(@Param("record") TbExperienceCourseDo record, @Param("example") TbExperienceCourseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Apr 17 20:47:13 CST 2019
     */
    int updateByPrimaryKeySelective(TbExperienceCourseDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_course
     *
     * @mbggenerated Wed Apr 17 20:47:13 CST 2019
     */
    int updateByPrimaryKey(TbExperienceCourseDo record);
}