package com.child.programming.base.mapper;

import com.child.programming.base.model.TbMaterialDto;
import com.child.programming.base.model.TbMaterialDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbMaterialDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int countByExample(TbMaterialDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByExample(TbMaterialDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insert(TbMaterialDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insertSelective(TbMaterialDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    List<TbMaterialDto> selectByExample(TbMaterialDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    TbMaterialDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbMaterialDto record, @Param("example") TbMaterialDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExample(@Param("record") TbMaterialDto record, @Param("example") TbMaterialDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKeySelective(TbMaterialDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKey(TbMaterialDto record);
}