package com.child.programming.base.mapper;

import com.child.programming.base.model.TbMaterialTypeDo;
import com.child.programming.base.model.TbMaterialTypeDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbMaterialTypeDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    int countByExample(TbMaterialTypeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    int deleteByExample(TbMaterialTypeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    int insert(TbMaterialTypeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    int insertSelective(TbMaterialTypeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    List<TbMaterialTypeDo> selectByExample(TbMaterialTypeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    TbMaterialTypeDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbMaterialTypeDo record, @Param("example") TbMaterialTypeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    int updateByExample(@Param("record") TbMaterialTypeDo record, @Param("example") TbMaterialTypeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    int updateByPrimaryKeySelective(TbMaterialTypeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    int updateByPrimaryKey(TbMaterialTypeDo record);
}