package com.child.programming.base.mapper;

import com.child.programming.base.model.TbPaymentRecordDo;
import com.child.programming.base.model.TbPaymentRecordDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbPaymentRecordDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int countByExample(TbPaymentRecordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int deleteByExample(TbPaymentRecordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int insert(TbPaymentRecordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int insertSelective(TbPaymentRecordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    List<TbPaymentRecordDo> selectByExample(TbPaymentRecordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    TbPaymentRecordDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbPaymentRecordDo record, @Param("example") TbPaymentRecordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int updateByExample(@Param("record") TbPaymentRecordDo record, @Param("example") TbPaymentRecordDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int updateByPrimaryKeySelective(TbPaymentRecordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int updateByPrimaryKey(TbPaymentRecordDo record);
}