package com.child.programming.base.mapper;

import com.child.programming.base.model.TbPaymentRecordDto;
import com.child.programming.base.model.TbPaymentRecordDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbPaymentRecordDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int countByExample(TbPaymentRecordDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByExample(TbPaymentRecordDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insert(TbPaymentRecordDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insertSelective(TbPaymentRecordDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    List<TbPaymentRecordDto> selectByExample(TbPaymentRecordDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    TbPaymentRecordDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbPaymentRecordDto record, @Param("example") TbPaymentRecordDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExample(@Param("record") TbPaymentRecordDto record, @Param("example") TbPaymentRecordDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKeySelective(TbPaymentRecordDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKey(TbPaymentRecordDto record);
}