package com.child.programming.base.mapper;

import com.child.programming.base.model.TbSchoolDto;
import com.child.programming.base.model.TbSchoolDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbSchoolDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int countByExample(TbSchoolDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByExample(TbSchoolDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insert(TbSchoolDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insertSelective(TbSchoolDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    List<TbSchoolDto> selectByExample(TbSchoolDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    TbSchoolDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbSchoolDto record, @Param("example") TbSchoolDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExample(@Param("record") TbSchoolDto record, @Param("example") TbSchoolDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKeySelective(TbSchoolDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKey(TbSchoolDto record);
}