package com.child.programming.base.mapper;

import com.child.programming.base.model.TbShareCircleDo;
import com.child.programming.base.model.TbShareCircleDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbShareCircleDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int countByExample(TbShareCircleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int deleteByExample(TbShareCircleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int insert(TbShareCircleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int insertSelective(TbShareCircleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    List<TbShareCircleDo> selectByExample(TbShareCircleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    TbShareCircleDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbShareCircleDo record, @Param("example") TbShareCircleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int updateByExample(@Param("record") TbShareCircleDo record, @Param("example") TbShareCircleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int updateByPrimaryKeySelective(TbShareCircleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    int updateByPrimaryKey(TbShareCircleDo record);
}