package com.child.programming.base.mapper;

import com.child.programming.base.model.TbShareCircleDto;
import com.child.programming.base.model.TbShareCircleDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbShareCircleDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int countByExample(TbShareCircleDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByExample(TbShareCircleDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insert(TbShareCircleDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insertSelective(TbShareCircleDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    List<TbShareCircleDto> selectByExample(TbShareCircleDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    TbShareCircleDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbShareCircleDto record, @Param("example") TbShareCircleDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExample(@Param("record") TbShareCircleDto record, @Param("example") TbShareCircleDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKeySelective(TbShareCircleDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_circle
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKey(TbShareCircleDto record);
}