package com.child.programming.base.mapper;

import com.child.programming.base.model.TbSignUpExperienceCourseDto;
import com.child.programming.base.model.TbSignUpExperienceCourseDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbSignUpExperienceCourseDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int countByExample(TbSignUpExperienceCourseDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByExample(TbSignUpExperienceCourseDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insert(TbSignUpExperienceCourseDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insertSelective(TbSignUpExperienceCourseDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    List<TbSignUpExperienceCourseDto> selectByExample(TbSignUpExperienceCourseDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    TbSignUpExperienceCourseDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbSignUpExperienceCourseDto record, @Param("example") TbSignUpExperienceCourseDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExample(@Param("record") TbSignUpExperienceCourseDto record, @Param("example") TbSignUpExperienceCourseDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKeySelective(TbSignUpExperienceCourseDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKey(TbSignUpExperienceCourseDto record);
}