package com.child.programming.base.mapper;

import com.child.programming.base.model.TbSignUpExperienceCourseDo;
import com.child.programming.base.model.TbSignUpExperienceCourseDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbSignUpExperienceCourseDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Fri Apr 19 20:24:06 CST 2019
     */
    int countByExample(TbSignUpExperienceCourseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Fri Apr 19 20:24:06 CST 2019
     */
    int deleteByExample(TbSignUpExperienceCourseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Fri Apr 19 20:24:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Fri Apr 19 20:24:06 CST 2019
     */
    int insert(TbSignUpExperienceCourseDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Fri Apr 19 20:24:06 CST 2019
     */
    int insertSelective(TbSignUpExperienceCourseDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Fri Apr 19 20:24:06 CST 2019
     */
    List<TbSignUpExperienceCourseDo> selectByExample(TbSignUpExperienceCourseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Fri Apr 19 20:24:06 CST 2019
     */
    TbSignUpExperienceCourseDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Fri Apr 19 20:24:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbSignUpExperienceCourseDo record, @Param("example") TbSignUpExperienceCourseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Fri Apr 19 20:24:06 CST 2019
     */
    int updateByExample(@Param("record") TbSignUpExperienceCourseDo record, @Param("example") TbSignUpExperienceCourseDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Fri Apr 19 20:24:06 CST 2019
     */
    int updateByPrimaryKeySelective(TbSignUpExperienceCourseDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up_experience_course
     *
     * @mbggenerated Fri Apr 19 20:24:06 CST 2019
     */
    int updateByPrimaryKey(TbSignUpExperienceCourseDo record);
}