package com.child.programming.base.mapper;

import com.child.programming.base.model.TbStudentCourseScheduleDo;
import com.child.programming.base.model.TbStudentCourseScheduleDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbStudentCourseScheduleDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int countByExample(TbStudentCourseScheduleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int deleteByExample(TbStudentCourseScheduleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int insert(TbStudentCourseScheduleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int insertSelective(TbStudentCourseScheduleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    List<TbStudentCourseScheduleDo> selectByExample(TbStudentCourseScheduleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    TbStudentCourseScheduleDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbStudentCourseScheduleDo record, @Param("example") TbStudentCourseScheduleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int updateByExample(@Param("record") TbStudentCourseScheduleDo record, @Param("example") TbStudentCourseScheduleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int updateByPrimaryKeySelective(TbStudentCourseScheduleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int updateByPrimaryKey(TbStudentCourseScheduleDo record);
}