package com.child.programming.base.mapper;

import com.child.programming.base.model.TbStudentSignUpDto;
import com.child.programming.base.model.TbStudentSignUpDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbStudentSignUpDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int countByExample(TbStudentSignUpDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByExample(TbStudentSignUpDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insert(TbStudentSignUpDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insertSelective(TbStudentSignUpDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    List<TbStudentSignUpDto> selectByExample(TbStudentSignUpDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    TbStudentSignUpDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbStudentSignUpDto record, @Param("example") TbStudentSignUpDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExample(@Param("record") TbStudentSignUpDto record, @Param("example") TbStudentSignUpDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKeySelective(TbStudentSignUpDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKey(TbStudentSignUpDto record);
}