package com.child.programming.base.mapper;

import com.child.programming.base.model.TbStudentSignUpDo;
import com.child.programming.base.model.TbStudentSignUpDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbStudentSignUpDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int countByExample(TbStudentSignUpDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int deleteByExample(TbStudentSignUpDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int insert(TbStudentSignUpDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int insertSelective(TbStudentSignUpDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    List<TbStudentSignUpDo> selectByExample(TbStudentSignUpDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    TbStudentSignUpDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbStudentSignUpDo record, @Param("example") TbStudentSignUpDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int updateByExample(@Param("record") TbStudentSignUpDo record, @Param("example") TbStudentSignUpDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int updateByPrimaryKeySelective(TbStudentSignUpDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_sign_up
     *
     * @mbggenerated Wed Apr 24 08:46:24 CST 2019
     */
    int updateByPrimaryKey(TbStudentSignUpDo record);
}