package com.child.programming.base.mapper;

import com.child.programming.base.model.TbStudentCourseScheduleDto;
import com.child.programming.base.model.TbStudentCourseScheduleDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbStudentCourseScheduleDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int countByExample(TbStudentCourseScheduleDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByExample(TbStudentCourseScheduleDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insert(TbStudentCourseScheduleDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insertSelective(TbStudentCourseScheduleDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    List<TbStudentCourseScheduleDto> selectByExample(TbStudentCourseScheduleDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    TbStudentCourseScheduleDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbStudentCourseScheduleDto record, @Param("example") TbStudentCourseScheduleDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExample(@Param("record") TbStudentCourseScheduleDto record, @Param("example") TbStudentCourseScheduleDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKeySelective(TbStudentCourseScheduleDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKey(TbStudentCourseScheduleDto record);
}