package com.child.programming.base.mapper;

import com.child.programming.base.model.TbTeacherCourseScheduleDto;
import com.child.programming.base.model.TbTeacherCourseScheduleDtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbTeacherCourseScheduleDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int countByExample(TbTeacherCourseScheduleDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByExample(TbTeacherCourseScheduleDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insert(TbTeacherCourseScheduleDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int insertSelective(TbTeacherCourseScheduleDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    List<TbTeacherCourseScheduleDto> selectByExample(TbTeacherCourseScheduleDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    TbTeacherCourseScheduleDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbTeacherCourseScheduleDto record, @Param("example") TbTeacherCourseScheduleDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByExample(@Param("record") TbTeacherCourseScheduleDto record, @Param("example") TbTeacherCourseScheduleDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKeySelective(TbTeacherCourseScheduleDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course_schedule
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    int updateByPrimaryKey(TbTeacherCourseScheduleDto record);
}