package com.child.programming.base.model;

import java.util.Date;

public class TbCourseDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.period_count
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    private Integer periodCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.code
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.max_capacity
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    private Integer maxCapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.money
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.telephone
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.introduction
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.photo_url
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.status
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.create_id
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.create_time
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.last_update_id
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    private Integer lastUpdateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.last_update_time
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.period_count
     *
     * @return the value of course.period_count
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public Integer getPeriodCount() {
        return periodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.period_count
     *
     * @param periodCount the value for course.period_count
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public void setPeriodCount(Integer periodCount) {
        this.periodCount = periodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.code
     *
     * @return the value of course.code
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.code
     *
     * @param code the value for course.code
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.max_capacity
     *
     * @return the value of course.max_capacity
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public Integer getMaxCapacity() {
        return maxCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.max_capacity
     *
     * @param maxCapacity the value for course.max_capacity
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public void setMaxCapacity(Integer maxCapacity) {
        this.maxCapacity = maxCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.money
     *
     * @return the value of course.money
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.money
     *
     * @param money the value for course.money
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.telephone
     *
     * @return the value of course.telephone
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.telephone
     *
     * @param telephone the value for course.telephone
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.introduction
     *
     * @return the value of course.introduction
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.introduction
     *
     * @param introduction the value for course.introduction
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.photo_url
     *
     * @return the value of course.photo_url
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.photo_url
     *
     * @param photoUrl the value for course.photo_url
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.status
     *
     * @return the value of course.status
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.status
     *
     * @param status the value for course.status
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.create_id
     *
     * @return the value of course.create_id
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.create_id
     *
     * @param createId the value for course.create_id
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.create_time
     *
     * @return the value of course.create_time
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.create_time
     *
     * @param createTime the value for course.create_time
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.last_update_id
     *
     * @return the value of course.last_update_id
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public Integer getLastUpdateId() {
        return lastUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.last_update_id
     *
     * @param lastUpdateId the value for course.last_update_id
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public void setLastUpdateId(Integer lastUpdateId) {
        this.lastUpdateId = lastUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.last_update_time
     *
     * @return the value of course.last_update_time
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.last_update_time
     *
     * @param lastUpdateTime the value for course.last_update_time
     *
     * @mbggenerated Wed Mar 13 16:01:54 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}