package com.child.programming.base.model;

import java.util.Date;

public class TbGradeDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.classroom_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Integer classroomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.course_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.name
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.teacher_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.max_capacity
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Integer maxCapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.description
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.current_period
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Integer currentPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.period_history
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private String periodHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.start_date
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.end_date
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.weekends_schedule
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private String weekendsSchedule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.status
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.create_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.create_time
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.last_update_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Integer lastUpdateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.last_update_time
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.id
     *
     * @return the value of grade.id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.id
     *
     * @param id the value for grade.id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.classroom_id
     *
     * @return the value of grade.classroom_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Integer getClassroomId() {
        return classroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.classroom_id
     *
     * @param classroomId the value for grade.classroom_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setClassroomId(Integer classroomId) {
        this.classroomId = classroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.course_id
     *
     * @return the value of grade.course_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.course_id
     *
     * @param courseId the value for grade.course_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.name
     *
     * @return the value of grade.name
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.name
     *
     * @param name the value for grade.name
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.teacher_id
     *
     * @return the value of grade.teacher_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.teacher_id
     *
     * @param teacherId the value for grade.teacher_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.max_capacity
     *
     * @return the value of grade.max_capacity
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Integer getMaxCapacity() {
        return maxCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.max_capacity
     *
     * @param maxCapacity the value for grade.max_capacity
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setMaxCapacity(Integer maxCapacity) {
        this.maxCapacity = maxCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.description
     *
     * @return the value of grade.description
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.description
     *
     * @param description the value for grade.description
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.current_period
     *
     * @return the value of grade.current_period
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Integer getCurrentPeriod() {
        return currentPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.current_period
     *
     * @param currentPeriod the value for grade.current_period
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setCurrentPeriod(Integer currentPeriod) {
        this.currentPeriod = currentPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.period_history
     *
     * @return the value of grade.period_history
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public String getPeriodHistory() {
        return periodHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.period_history
     *
     * @param periodHistory the value for grade.period_history
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setPeriodHistory(String periodHistory) {
        this.periodHistory = periodHistory == null ? null : periodHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.start_date
     *
     * @return the value of grade.start_date
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.start_date
     *
     * @param startDate the value for grade.start_date
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.end_date
     *
     * @return the value of grade.end_date
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.end_date
     *
     * @param endDate the value for grade.end_date
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.weekends_schedule
     *
     * @return the value of grade.weekends_schedule
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public String getWeekendsSchedule() {
        return weekendsSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.weekends_schedule
     *
     * @param weekendsSchedule the value for grade.weekends_schedule
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setWeekendsSchedule(String weekendsSchedule) {
        this.weekendsSchedule = weekendsSchedule == null ? null : weekendsSchedule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.status
     *
     * @return the value of grade.status
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.status
     *
     * @param status the value for grade.status
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.create_id
     *
     * @return the value of grade.create_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.create_id
     *
     * @param createId the value for grade.create_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.create_time
     *
     * @return the value of grade.create_time
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.create_time
     *
     * @param createTime the value for grade.create_time
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.last_update_id
     *
     * @return the value of grade.last_update_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Integer getLastUpdateId() {
        return lastUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.last_update_id
     *
     * @param lastUpdateId the value for grade.last_update_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setLastUpdateId(Integer lastUpdateId) {
        this.lastUpdateId = lastUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.last_update_time
     *
     * @return the value of grade.last_update_time
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.last_update_time
     *
     * @param lastUpdateTime the value for grade.last_update_time
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}