package com.child.programming.base.model;

import java.util.Date;

public class TbMaterialTypeDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_type.id
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_type.name
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_type.comment
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_type.status
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_type.create_id
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_type.create_time
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_type.last_update_id
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    private Integer lastUpdateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_type.last_update_time
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_type.id
     *
     * @return the value of material_type.id
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_type.id
     *
     * @param id the value for material_type.id
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_type.name
     *
     * @return the value of material_type.name
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_type.name
     *
     * @param name the value for material_type.name
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_type.comment
     *
     * @return the value of material_type.comment
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_type.comment
     *
     * @param comment the value for material_type.comment
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_type.status
     *
     * @return the value of material_type.status
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_type.status
     *
     * @param status the value for material_type.status
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_type.create_id
     *
     * @return the value of material_type.create_id
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_type.create_id
     *
     * @param createId the value for material_type.create_id
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_type.create_time
     *
     * @return the value of material_type.create_time
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_type.create_time
     *
     * @param createTime the value for material_type.create_time
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_type.last_update_id
     *
     * @return the value of material_type.last_update_id
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public Integer getLastUpdateId() {
        return lastUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_type.last_update_id
     *
     * @param lastUpdateId the value for material_type.last_update_id
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public void setLastUpdateId(Integer lastUpdateId) {
        this.lastUpdateId = lastUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_type.last_update_time
     *
     * @return the value of material_type.last_update_time
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_type.last_update_time
     *
     * @param lastUpdateTime the value for material_type.last_update_time
     *
     * @mbggenerated Thu Apr 11 10:22:29 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}