package com.child.programming.base.model;

import java.util.Date;

public class TbReportDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.grade_id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.student_id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.teacher_id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.hand_ability
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    private String handAbility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.focus_on
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    private String focusOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.knowledge
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    private String knowledge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.evaluate_text
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    private String evaluateText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.create_id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.create_time
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.last_update_id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    private Integer lastUpdateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.last_update_time
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.status
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.id
     *
     * @return the value of report.id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.id
     *
     * @param id the value for report.id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.grade_id
     *
     * @return the value of report.grade_id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.grade_id
     *
     * @param gradeId the value for report.grade_id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.student_id
     *
     * @return the value of report.student_id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.student_id
     *
     * @param studentId the value for report.student_id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.teacher_id
     *
     * @return the value of report.teacher_id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.teacher_id
     *
     * @param teacherId the value for report.teacher_id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.hand_ability
     *
     * @return the value of report.hand_ability
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public String getHandAbility() {
        return handAbility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.hand_ability
     *
     * @param handAbility the value for report.hand_ability
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public void setHandAbility(String handAbility) {
        this.handAbility = handAbility == null ? null : handAbility.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.focus_on
     *
     * @return the value of report.focus_on
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public String getFocusOn() {
        return focusOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.focus_on
     *
     * @param focusOn the value for report.focus_on
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public void setFocusOn(String focusOn) {
        this.focusOn = focusOn == null ? null : focusOn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.knowledge
     *
     * @return the value of report.knowledge
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public String getKnowledge() {
        return knowledge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.knowledge
     *
     * @param knowledge the value for report.knowledge
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public void setKnowledge(String knowledge) {
        this.knowledge = knowledge == null ? null : knowledge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.evaluate_text
     *
     * @return the value of report.evaluate_text
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public String getEvaluateText() {
        return evaluateText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.evaluate_text
     *
     * @param evaluateText the value for report.evaluate_text
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public void setEvaluateText(String evaluateText) {
        this.evaluateText = evaluateText == null ? null : evaluateText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.create_id
     *
     * @return the value of report.create_id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.create_id
     *
     * @param createId the value for report.create_id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.create_time
     *
     * @return the value of report.create_time
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.create_time
     *
     * @param createTime the value for report.create_time
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.last_update_id
     *
     * @return the value of report.last_update_id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public Integer getLastUpdateId() {
        return lastUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.last_update_id
     *
     * @param lastUpdateId the value for report.last_update_id
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public void setLastUpdateId(Integer lastUpdateId) {
        this.lastUpdateId = lastUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.last_update_time
     *
     * @return the value of report.last_update_time
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.last_update_time
     *
     * @param lastUpdateTime the value for report.last_update_time
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.status
     *
     * @return the value of report.status
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.status
     *
     * @param status the value for report.status
     *
     * @mbggenerated Tue May 14 14:04:29 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}