package com.child.programming.base.model;

import java.util.Date;

public class TbRoleDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.comment
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.status
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.create_id
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.create_time
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.last_update_id
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    private Integer lastUpdateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.last_update_time
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_token
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    private String roleToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.comment
     *
     * @return the value of role.comment
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.comment
     *
     * @param comment the value for role.comment
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.status
     *
     * @return the value of role.status
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.status
     *
     * @param status the value for role.status
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.create_id
     *
     * @return the value of role.create_id
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.create_id
     *
     * @param createId the value for role.create_id
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.create_time
     *
     * @return the value of role.create_time
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.create_time
     *
     * @param createTime the value for role.create_time
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.last_update_id
     *
     * @return the value of role.last_update_id
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public Integer getLastUpdateId() {
        return lastUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.last_update_id
     *
     * @param lastUpdateId the value for role.last_update_id
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public void setLastUpdateId(Integer lastUpdateId) {
        this.lastUpdateId = lastUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.last_update_time
     *
     * @return the value of role.last_update_time
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.last_update_time
     *
     * @param lastUpdateTime the value for role.last_update_time
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_token
     *
     * @return the value of role.role_token
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public String getRoleToken() {
        return roleToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_token
     *
     * @param roleToken the value for role.role_token
     *
     * @mbggenerated Wed Apr 17 14:34:29 CST 2019
     */
    public void setRoleToken(String roleToken) {
        this.roleToken = roleToken == null ? null : roleToken.trim();
    }
}