package com.child.programming.base.model;

import java.util.Date;

public class TbSignUpExperienceCourseDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up_experience_course.id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up_experience_course.experience_course_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Integer experienceCourseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up_experience_course.student_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up_experience_course.sign_up_time
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Date signUpTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up_experience_course.status
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up_experience_course.create_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up_experience_course.create_time
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up_experience_course.last_update_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Integer lastUpdateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up_experience_course.last_update_time
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up_experience_course.id
     *
     * @return the value of sign_up_experience_course.id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up_experience_course.id
     *
     * @param id the value for sign_up_experience_course.id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up_experience_course.experience_course_id
     *
     * @return the value of sign_up_experience_course.experience_course_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Integer getExperienceCourseId() {
        return experienceCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up_experience_course.experience_course_id
     *
     * @param experienceCourseId the value for sign_up_experience_course.experience_course_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setExperienceCourseId(Integer experienceCourseId) {
        this.experienceCourseId = experienceCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up_experience_course.student_id
     *
     * @return the value of sign_up_experience_course.student_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up_experience_course.student_id
     *
     * @param studentId the value for sign_up_experience_course.student_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up_experience_course.sign_up_time
     *
     * @return the value of sign_up_experience_course.sign_up_time
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Date getSignUpTime() {
        return signUpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up_experience_course.sign_up_time
     *
     * @param signUpTime the value for sign_up_experience_course.sign_up_time
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setSignUpTime(Date signUpTime) {
        this.signUpTime = signUpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up_experience_course.status
     *
     * @return the value of sign_up_experience_course.status
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up_experience_course.status
     *
     * @param status the value for sign_up_experience_course.status
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up_experience_course.create_id
     *
     * @return the value of sign_up_experience_course.create_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up_experience_course.create_id
     *
     * @param createId the value for sign_up_experience_course.create_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up_experience_course.create_time
     *
     * @return the value of sign_up_experience_course.create_time
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up_experience_course.create_time
     *
     * @param createTime the value for sign_up_experience_course.create_time
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up_experience_course.last_update_id
     *
     * @return the value of sign_up_experience_course.last_update_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Integer getLastUpdateId() {
        return lastUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up_experience_course.last_update_id
     *
     * @param lastUpdateId the value for sign_up_experience_course.last_update_id
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setLastUpdateId(Integer lastUpdateId) {
        this.lastUpdateId = lastUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up_experience_course.last_update_time
     *
     * @return the value of sign_up_experience_course.last_update_time
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up_experience_course.last_update_time
     *
     * @param lastUpdateTime the value for sign_up_experience_course.last_update_time
     *
     * @mbggenerated Mon Mar 25 19:37:56 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}